name: Docs

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r requirements-doc.txt

      - name: Install mpl-gui
        run: python -m pip install -v .
      - name: Build
        run: make -Cdocs singlehtml
      - name: Publish
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/singlehtml
          force_orphan: true
